# Generated by Django 5.1.1 on 2024-12-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreInstituciones', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nroPersonas', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fechaInscripcion', models.DateField()),
                ('horaInscripcion', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=25)),
                ('observacion', models.CharField(max_length=60)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodriguez_diegoAPP_FINAL.instituciones')),
            ],
        ),
    ]
